ALTER TABLE IF EXISTS community_questions
    ADD COLUMN IF NOT EXISTS moderation_status
    ENUM ('PENDING', 'PUBLISHED', 'REJECTED') DEFAULT 'PUBLISHED' NOT NULL;

ALTER TABLE IF EXISTS community_replies
    ADD COLUMN IF NOT EXISTS author_role
    ENUM ('USER', 'ADMIN') DEFAULT 'USER' NOT NULL;
